version: 2

models:
  - name: stg_users
    columns:
      - name: id
      - name: name
      - name: email

  - name: stg_orders
    columns:
      - name: id
      - name: user_id
      - name: amount
