static_assets_path: console/consoleui/build
tenant_sub_domain: tenant.dev.userclouds.tools:3333
tenant_protocol: https

console_url: https://console.dev.userclouds.tools:3333

log_db:
  user: userclouds
  dbname: status_00000000000000000000000000000000
  host: localhost
  dbdriver: postgres
  dbproduct: postgres
  port: 26257

svc_listener:
  protocol: http
  host: localhost
  port: 5300

console_tenant_id: 41ab79a8-0dff-418e-9d42-e1694469120a

worker_client:
  type: test
