apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "authz.serviceAccount" . }}
  labels:
     {{- include "userclouds.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.roles.authz }}
    eks.amazonaws.com/role-arn: {{ toYaml . }}
    {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.authz.replicas | default .Values.authz.replicas }}
  selector:
    matchLabels:
      {{- include "authz.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        userclouds.sla: critical
        {{- include "authz.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.authz.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authz.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "authz.serviceAccount" . }}
      volumes:
        - name: configmap
          configMap:
            name: userclouds-configs
            items:
              - key: base
                path: {{ printf "base_%s.yaml" .Values.universe }}
              - key: authz
                path: {{ printf "authz/%s.yaml" .Values.universe }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: authz
          image: "{{ include "userclouds.image" . }}"
          imagePullPolicy: IfNotPresent
          {{- with .Values.tools.workingDir }}
          workingDir: {{ toYaml . }}
          {{- end }}
          {{- with .Values.authz.command }}
          command:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.authz.args }}
          args:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- include "userclouds.envConfigMap" . | nindent 10 }}
          env:
            {{- include "userclouds.envVars" . | nindent 10 }}
          {{- with .Values.authz.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- include "userclouds.lifecycleDrain" . | nindent 10 }}
          volumeMounts:
            - name: configmap
              mountPath: /userclouds/configmaps
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: authz
              containerPort: 5000
              protocol: TCP
            - name: internal
              containerPort: 5001
              protocol: TCP
          {{- if .Values.authz.healthchecks }}
          livenessProbe:
            initialDelaySeconds: 240
            httpGet:
              path: /healthcheck
              port: authz
          readinessProbe:
            initialDelaySeconds: 240
            httpGet:
              path: /healthcheck
              port: authz
          {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: authz
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
      {{- include "authz.selectorLabels" . | nindent 6 }}
  ports:
    - name: service
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: internal
      protocol: TCP
      port: 5001

