apiVersion: v1
kind: ConfigMap
metadata:
  name: userclouds-configs
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
data:
  {{- with .Values.config.base }}
  base: | {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.config.checkattribute }}
  checkattribute: | {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.config.authz }}
  authz: | {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.config.logserver }}
  logserver: | {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.config.idp }}
  idp: | {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.config.worker }}
  worker: | {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.config.console }}
  console: | {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.config.plex }}
  plex: | {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.config.rootdb }}
  rootdb: | {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.config.rootdbstatus }}
  rootdbstatus: | {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: userclouds-provisioning
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
data:
  tenant_console.json.tmpl: |-
    {{- tpl ($.Files.Get "files/provisioning/tenant_console.json.tmpl") . | nindent 4 }}
  company.json.tmpl: |-
    {{- tpl ($.Files.Get "files/provisioning/company.json.tmpl") . | nindent 4 }}
