apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "plex.serviceAccount" . }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.roles.plex }}
    eks.amazonaws.com/role-arn: {{ toYaml . }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configs.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.plex.replicas | default .Values.plex.replicas }}
  selector:
    matchLabels:
      {{- include "plex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        userclouds.sla: critical
        {{- include "plex.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.plex.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.plex.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.plex.serviceAccountName }}
      serviceAccountName: {{ toYaml . }}
      {{- end }}
      volumes:
        - name: configmap
          configMap:
            name: userclouds-configs
            items:
              - key: base
                path: {{ printf "base_%s.yaml" .Values.universe }}
              - key: plex
                path: {{ printf "plex/%s.yaml" .Values.universe }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: plex
          image: "{{ include "userclouds.image" . }}"
          imagePullPolicy: IfNotPresent
          {{- with .Values.tools.workingDir }}
          workingDir: {{ toYaml . }}
          {{- end }}
          {{- with .Values.plex.command }}
          command:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.plex.args }}
          args:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- include "userclouds.envConfigMap" . | nindent 10 }}
          env:
            {{- include "userclouds.envVars" . | nindent 10 }}
            {{- with .Values.extraEnv }}
            {{ toYaml . | nindent 10 }}
            {{- end }}
          {{- with .Values.plex.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- include "userclouds.lifecycleDrain" . | nindent 10 }}
          volumeMounts:
            - name: configmap
              mountPath: /userclouds/configmaps
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: plex
              containerPort: 5000
              protocol: TCP
            - name: internal
              containerPort: 5001
              protocol: TCP
          {{- with .Values.plex.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.plex.livenessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
      {{- include "plex.selectorLabels" . | nindent 6 }}
  ports:
    - name: service
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: internal
      protocol: TCP
      port: 5001
