---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: provisioner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: provisioner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: provisioner
subjects:
  - kind: ServiceAccount
    name: provisioner
    namespace: {{ .Release.Namespace }}