---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: userclouds-read
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: userclouds-read
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: userclouds-read
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: userclouds-read
subjects:
  - kind: ServiceAccount
    name: userclouds-read
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: userclouds-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: userclouds-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: userclouds-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: userclouds-admin
subjects:
  - kind: ServiceAccount
    name: userclouds-admin
    namespace: {{ .Release.Namespace }}