apiVersion: v1
kind: Service
metadata:
  name: tenant
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
      {{- include "plex.selectorLabels" . | nindent 6 }}
  ports:
    - name: service
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: internal
      protocol: TCP
      port: 5001
