company_db:
  user: userclouds
  password: aws://secrets/prod/console/cdb_password
  dbname: companyconfig
  host: XXXXXXX.global.rds.amazonaws.com
  dbdriver: postgres
  dbproduct: aws-aurora-postgres
  port: 5432
  regional_hosts:
    aws-us-west-2: XXXXXXX.us-west-2.rds.amazonaws.com
    aws-us-east-1: XXXXXXX.us-east-1.rds.amazonaws.com
    aws-eu-west-1: XXXXXXX.eu-west-1.rds.amazonaws.com

svc_listener:
  protocol: http
  host: 0.0.0.0
  port: 5000

internal_server:
  protocol: http
  host: 0.0.0.0
  port: 5001

tracing:
  # see terraform/modules/userclouds/grafana-alloy/main.tf
  collector_host: alloy.observability.svc.cluster.local:4317

featureflags:
  api_key: aws://secrets/prod/statsig/v1
  verbose: false

sentry:
  dsn: https://XXXXXXX.ingest.sentry.io/XXXXXXX
  traces_sample_rate: 0.1

cache:
  redis_caches:
    - region: aws-us-east-1
      host: XXXXXXX.cache.amazonaws.com
      port: 6379
      dbname: 0
      username: prod-user
      password: aws://secrets/prod/redis_user_password
    - region: aws-us-west-2
      host: XXXXXXX.cache.amazonaws.com
      port: 6379
      dbname: 0
      username: prod-user
      password: aws://secrets/prod/redis_user_password
    - region: aws-eu-west-1
      host: XXXXXXX.cache.amazonaws.com
      port: 6379
      dbname: 0
      username: prod-user
      password: aws://secrets/prod/redis_user_password

logger:
  transports:
    - type: goLogJSON
      transportconfig:
        required: true
        max_log_level: 5
    - type: server
      transportconfig:
        required: true
        max_log_level: 5
      tenant_id: 804718b8-5788-4c31-9f5e-1ac55782728c
      log_service_url: 'http://logserver.userclouds.svc.cluster.local'
      send_raw_data: false
    - type: kinesis
      aws_region: 'us-west-2'
      stream_name: 'prod'
      shard_count: 12
      transportconfig:
        required: false
        max_log_level: 5
    - type: eventMetrics
      transportconfig:
        required: false
        max_log_level: 5
