apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - localstack.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/group: localstack
      app.kubernetes.io/managed-by: kustomize