apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- cert-manager-crd.yaml
- cert-manager.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/group: cert-manager
    app.kubernetes.io/managed-by: kustomize
