apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    replicationRole: primary
  name: postgres
  namespace: userclouds
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
    replicationRole: primary
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    replicationRole: primary
  name: postgres-np
  namespace: userclouds
spec:
  type: NodePort
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  ports:
    - port: 5433
      targetPort: 5432
      nodePort: 30100
  selector:
    app: postgres
    replicationRole: primary
