# Credentials for the root database user. must match what we use in CI, defined in .github/workflows/golang-ci.yml
db:
  user: userclouds_test_root
  password: dev-literal://m4u4N87cqcLJpGsQ
  dbname: postgres
  host: localhost
  dbdriver: postgres
  dbproduct: postgres
  port: 5432
