db:
  user: userclouds
  password: aws://secrets/staging/console/cdb_password
  dbname: companyconfig
  host: aurora-global-staging.global-ghfsmzcj8xvp.global.rds.amazonaws.com
  dbdriver: postgres
  dbproduct: aws-aurora-postgres
  port: 5432
  regional_hosts:
    aws-us-west-2: aurora-cluster-staging-us-west-2.cluster-ro-crjyptgsmywz.us-west-2.rds.amazonaws.com
    aws-us-east-1: aurora-cluster-staging-us-east-1.cluster-ro-cly2gyqwkgwv.us-east-1.rds.amazonaws.com
    aws-eu-west-1: aurora-cluster-staging-eu-west-1.cluster-ro-czuwq4cws4zt.eu-west-1.rds.amazonaws.com
