log_db:
  user: userclouds_test_root
  password: dev-literal://m4u4N87cqcLJpGsQ
  dbname: status_00000000000000000000000000000000
  host: localhost
  dbdriver: postgres
  dbproduct: postgres
  port: 5432

svc_listener:
  protocol: http
  host: localhost
  port: 5500

console_tenant_id: 41ab79a8-0dff-418e-9d42-e1694469120a
