log_db:
  user: usercloudstage
  password: aws://secrets/staging/logserver/rdb_password_only
  dbname: status_00000000000000000000000000000000
  dbdriver: postgres
  dbproduct: aws-rds-postgres
  host: status-staging-postgre.c3cgcihdah0v.us-west-2.rds.amazonaws.com
  port: 5432

svc_listener:
  protocol: http
  host: 0.0.0.0
  port: 5500

logger:
  transports:
    - type: kinesis
      aws_region: 'us-west-2'
      stream_name: 'staging-log'
      shard_count: 1
      transportconfig:
        required: true
        max_log_level: 5

console_tenant_id: 03c1d5f7-50ef-4723-9a37-3bf0dc301842
kinesis_aws_region: us-west-2
