log_db:
  user: unused
  password: dev-literal://unused
  dbname: unused
  host: unused
  port: 1234
  dbdriver: postgres
  dbproduct: postgres

svc_listener:
  protocol: http
  host: localhost
  port: 5500

console_tenant_id: 41ab79a8-0dff-418e-9d42-e1694469120a
