{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: userclouds
  labels:
    {{- include "userclouds.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: internal
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "userclouds.labels" . | nindent 6 }}
{{- end }}
