log_db:
  user: postgres
  dbname: status_00000000000000000000000000000000
  host: localhost
  dbdriver: postgres
  dbproduct: postgres
  port: 5432

svc_listener:
  protocol: http
  host: localhost
  port: 3012

internal_server:
  protocol: http
  host: 127.0.0.1
  port: 3014

console_tenant_id: 41ab79a8-0dff-418e-9d42-e1694469120a

worker_client:
  type: http
  url: http://worker:3012