region: customerlocal
universe: onprem
domain: '{{ .Release.Namespace }}.svc.cluster.local'
company_id: 1ee4497e-c326-4068-94ed-3dcdaaaa53bc
console_tenant_id: 41ab79a8-0dff-418e-9d42-e1694469120a
company_name: userclouds
admin_user_email: "admin@example.org"
google_client_id: "clientid"

image:
  repository: ctxsh/userclouds
  tag: 2025-10-12.01

protocol: http

extraVolumeMounts: {}
extraVolumes: {}

#-- Only enabled in a single region.
enableCronJobs: false

# Change to termination grace seconds.
preStopSleepSeconds: 15

roles: {}

tools:
  enabled: true
  serviceAccountName: userclouds-admin
  resources:
    requests:
      cpu: 0.4
      memory: 512Mi

#-- Plex service
plex:
  replicas: 1
  serviceAccountName: userclouds-read
  args:
    - plex
  # pdb:
  #   minAvailable: 2
  resources:
    requests:
      cpu: 0.4
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: plex
  readinessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: plex

userstore:
  replicas: 1
  serviceAccountName: userclouds-read
  args:
    - idp
  # pdb:
  #   minAvailable: 2
  resources:
    requests:
      cpu: 0.4
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: userstore
  readinessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: userstore

#-- Console service
console:
  replicas: 1
  serviceAccountName: userclouds-read
  args:
    - console
  # pdb:
  #   minAvailable: 2
  resources:
    requests:
      cpu: 0.4
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: console
  readinessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: console

#-- Logserver service
logserver:
  replicas: 1
  serviceAccountName: userclouds-read
  args:
    - logserver
  # pdb:
  #   minAvailable: 2
  resources:
    requests:
      cpu: 0.4
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: logserver
  readinessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: logserver

#-- Authz service
authz:
  replicas: 1
  serviceAccountName: userclouds-read
  args:
    - authz
  # pdb:
  #   minAvailable: 2
  resources:
    requests:
      cpu: 0.4
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: authz
  readinessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: authz

#-- Worker service
worker:
  replicas: 1
  serviceAccountName: userclouds-read
  args:
    - worker
  # pdb:
  #   minAvailable: 2
  resources:
    requests:
      cpu: 0.4
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 30
    initialDelaySeconds: 10
    periodSeconds: 10
    httpGet:
      path: /healthcheck
      port: worker
    successThreshold: 1
    failureThreshold: 10
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    httpGet:
      path: /healthcheck
      port: worker

#-- Checkattributes service
checkattribute:
  enabled: false
  serviceAccountName: userclouds-read
  replicas: 1
  # pdb:
  #   minAvailable: 2
  #-- TODO: figure out what this is for.
  livenessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: checkattribute
  readinessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: checkattribute
  deployments:
    - name: envtest
      replicas: 1
      resources:
        limits:
          cpu: 0.5
          memory: 256Mi
        requests:
          cpu: 0.4
          memory: 512Mi

# TODO: Pull out into common db components (at the very least the db config).
config:
  #-- Authz service configuration
  authz:
    console_tenant_id: '{{ tpl .Values.console_tenant_id . }}'
  #-- Base
  base:
    company_db: # Using postgres in container env, user/pw must match docker/userclouds-headless/docker-compose.yaml
      user: postgres
      password: env://PG_PASSWORD
      dbname: companyconfig
      host: postgres
      dbdriver: postgres
      dbproduct: postgres
      port: 5432
    svc_listener:
      protocol: http
      host: 0.0.0.0
      port: 5000
    internal_server:
      protocol: http
      host: 0.0.0.0
      port: 5001
    logger:
      transports:
        - type: goLogJSON
          transportconfig:
            required: true
            max_log_level: 5

  #-- Checkattribute service configuration
  checkattribute:
    console_tenant_id: '{{ tpl .Values.console_tenant_id . }}'

  #-- Console service configuration
  console:
    static_assets_path: /userclouds/uiassets/console/
    console_url: '{{ include "userclouds.console.url" $ }}'
    log_db:
      user: postgres
      password: env://PG_PASSWORD
      dbname: status_fake
      host: postgres
      dbdriver: postgres
      dbproduct: postgres
      port: 5432
    console_tenant_id: '{{ tpl .Values.console_tenant_id . }}'
    tenant_sub_domain: 'tenant.{{ tpl .Values.domain . }}'
    tenant_protocol: http
    worker_client:
      type: http
      url: http://localhost:3012

  #-- IDP service configuration
  idp:
    console_tenant_id: '{{ tpl .Values.console_tenant_id . }}'
  #-- Logserver configuration
  logserver:
    log_db:
      user: postgres
      password: env://PG_PASSWORD
      dbname: status_00000000000000000000000000000000
      host: postgres
      dbdriver: postgres
      dbproduct: postgres
      port: 5432
    svc_listener:
      protocol: http
      host: localhost
      port: 5500
    console_tenant_id: '{{ tpl .Values.console_tenant_id . }}'

  #-- Plex configuration
  plex:
    console_tenant_id: '{{ tpl .Values.console_tenant_id . }}'
    static_assets_path: /userclouds/uiassets/plex/
    disable_email: true
    worker_client:
      type: http

  #-- Root database configuration
  rootdb:
    db:
      user: postgres
      password: env://PG_PASSWORD
      dbname: defaultdb
      host: postgres
      dbdriver: postgres
      dbproduct: postgres
      port: 5432

  #-- Root database status configuration
  rootdbstatus:
    db:
      user: postgres
      password: env://PG_PASSWORD
      dbname: rootdbstatus
      host: postgres
      dbdriver: postgres
      dbproduct: postgres
      port: 5432

  #-- Worker configuration
  worker:
    log_db:
      user: postgres
      password: env://PG_PASSWORD
      dbname: status_00000000000000000000000000000000
      host: postgres
      dbdriver: postgres
      dbproduct: postgres
      port: 5432
    dns:
      host_and_port: 1.1.1.1:53
    console_tenant_id: '{{ tpl .Values.console_tenant_id . }}'
    worker_client:
      type: http
      url: http://localhost:3012
#    svc_listener:
#      protocol: http
#      host: localhost
#      port: 3012
#    console_tenant_id: '{{ tpl .Values.console_tenant_id . }}'
#    dns:
#      host_and_port: 1.1.1.1:53
#    worker_client:
#      type: http
#      url: http://localhost:3012
