image:
  repository: golang
  tag: 1.24-bookworm@sha256:3ce988c30fa67dc966ca716ee0ce7ad08d7330573e808cb68ada7e419bdf23de

tools:
  workingDir: /usr/src/app
  resources:
    limits:
      cpu: 2
      memory: 2048Mi
    requests:
      cpu: 2
      memory: 2048Mi

authz:
  workingDir: /usr/src/app
  command:
    - go
    - run
    - ./userclouds/cmd/main.go
  livenessProbe:
    initialDelaySeconds: 180
  readinessProbe:
    initialDelaySeconds: 180

worker:
  workingDir: /usr/src/app
  command:
    - go
    - run
    - ./userclouds/cmd/main.go
  livenessProbe:
    initialDelaySeconds: 180
  readinessProbe:
    initialDelaySeconds: 180

plex:
  workingDir: /usr/src/app
  command:
    - go
    - run
    - ./userclouds/cmd/main.go
  livenessProbe:
    initialDelaySeconds: 180
  readinessProbe:
    initialDelaySeconds: 180

console:
  workingDir: /usr/src/app
  command:
    - go
    - run
    - ./userclouds/cmd/main.go
  livenessProbe:
    initialDelaySeconds: 180
  readinessProbe:
    initialDelaySeconds: 180

userstore:
  workingDir: /usr/src/app
  command:
    - go
    - run
    - ./userclouds/cmd/main.go
  livenessProbe:
    initialDelaySeconds: 180
  readinessProbe:
    initialDelaySeconds: 180

# Local directory that is mounted through k3d
extraVolumes:
  - name: app
    hostPath:
      path: /app

extraVolumeMounts:
  - name: app
    mountPath: /usr/src/app
    readOnly: true

extraEnv:
  - name: PG_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: superUserPassword
