waf_acl_arn: arn:aws:wafv2:us-west-2:XXXXXX
# Created by terraform/configurations/aws/eks-cluster.hcl and terraform/modules/aws/eks-cluster/main.tf (alb_logs_bucket)
alb_logs_bucket: userclouds-prod-us-west-2-alb-logs
replicas: 3
pdb:
  minAvailable: 3
region: aws-us-west-2
enableCronJobs: true
preStopSleepSeconds: 15
config:
  dbproxy:
    health_check_port: 8080
    postgres_ports: [5433, 5434]
    mysql_ports: [3306, 3308, 3309]
plex:
  replicas: 4
dbproxy:
  enabled: true
  resources:
    limits:
      cpu: 0.5
      memory: 512Mi
    requests:
      cpu: 0.4
      memory: 256Mi
  ingress:
    scheme: internet-facing
    domain: dbproxy.userclouds.com
userstore:
  dont_allow_t3: true
  resources:
    limits:
      cpu: 0.5
      memory: 256Mi
    requests:
      cpu: 0.4
      memory: 128Mi
console: {}
logserver:
  replicas: 4
authz:
  dont_allow_t3: true
  replicas: 6
  resources:
    limits:
      cpu: 1.0
      memory: 512Mi
    requests:
      cpu: 0.8
      memory: 384Mi
checkattribute:
  enabled: true
  deployments:
    - name: union
      replicas: 3
      resources:
        limits:
          cpu: 2.0
          memory: 1536Mi # 1.5Gi
        requests:
          cpu: 1.5
          memory: 1Gi
