waf_acl_arn: arn:aws:wafv2:us-west-2:XXXXXX
# Created by terraform/configurations/aws/eks-cluster.hcl and terraform/modules/aws/eks-cluster/main.tf (alb_logs_bucket)
alb_logs_bucket: userclouds-staging-us-west-2-alb-logs
replicas: 3
pdb:
  minAvailable: 2
region: aws-us-west-2
enableCronJobs: true
preStopSleepSeconds: 15
config:
  dbproxy:
    health_check_port: 8080
    mysql_ports: [3308, 3309, 3310]
    postgres_ports: [5433, 5434, 5435]
plex: {}
dbproxy:
  enabled: true
  resources:
    limits:
      cpu: 0.5
      memory: 512Mi
    requests:
      cpu: 0.4
      memory: 256Mi
  ingress:
    scheme: internet-facing
    domain: dbproxy.staging.userclouds.com
userstore:
  dont_allow_t3: true
  resources:
    limits:
      cpu: 0.5
      memory: 512Mi
    requests:
      cpu: 0.4
      memory: 256Mi
console: {}
logserver: {}
authz:
  dont_allow_t3: true
  resources:
    limits:
      cpu: 0.5
      memory: 256Mi
    requests:
      cpu: 0.4
      memory: 128Mi
checkattribute:
  enabled: true
  deployments:
    - name: envtest
      replicas: 1
      resources:
        limits:
          cpu: 0.5
          memory: 256Mi
        requests:
          cpu: 0.4
          memory: 128Mi
